web: vendor/bin/heroku-php-apache2 public/
release: sh -c 'php scripts/prepare-cloud-deployment.php && php artisan migrate --force --no-interaction && (php artisan storage:link || true)'
worker: php artisan queue:work --sleep=3 --tries=3
